version: "3"
services:
  nginx:
    image: nginx:my_nginx
    build: ./requirements/nginx
    restart: always

  mariadb:
    image: maria_db:my_mariadb
    build: ./requirements/mariadb
    restart: always

  wordpress:
    image: wordpress:my_wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
